version: '3.8'

services:
  app:
    image: docker.io/johnnyhuy/seek-test-application:v0.0.1 # SemVer
    build:
      context: test-application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DS_HOST=${DS_HOST}
      - DS_DBNAME=${DS_DBNAME}
      - DS_USER=${DS_USER}
      - DS_PASSWORD=${DS_PASSWORD}
      - DS_PORT=${DS_PORT}
    depends_on:
      - database

  database:
    image: docker.io/postgres:12 # Its version is supported on AWS
    ports:
      - "${DS_PORT}:${DS_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DS_PASSWORD}
      - POSTGRES_USER=${DS_USER}
      - POSTGRES_DB=${DS_DBNAME}
