version: '3.8'

services:
  app:
    image: docker.io/johnnyhuy/seek-test-application:v0.0.1 # SemVer
    build:
      context: test-application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: docker.io/postgres:13 # Its version is supported on AWS
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
      - POSTGRES_DB=test
